apiVersion: v1
kind: Pod
metadata:
  name: my_pod
spec:
  containers:
  - image: flask_simple_webapp
    name: my_pod
    ports:
    - containerPort: 8081
    env:
    - name: APP_COLOR
      value: "pink"

status: {}